### ISSUE TITLE
Create  🌊System Flowchart

### ISSUE THREAD

**Issue by ralphcajipe** [ralphcajipe/BookstoreSystem#14]
### Use https://app.diagrams.net/

See Sir's requirement in using this method https://www.opentextbooks.org.hk/ditatopic/25251 for preparing system flowcharts:

### Example
![Image](https://user-images.githubusercontent.com/50406636/176993401-19fefd9f-c0b6-4bf0-8f6f-8b0187703174.png)

**Comment by ralphcajipe** [comment]
Anyone who can start our system flowchart?

**Comment by Acclanugget** [comment]
I can help at monday since I am busy this weekend and haven't brought my laptop to the countryside.

**Comment by ralphcajipe** [comment]
Thanks Jeremiah! Assigning you now for our system flowchart. Just check the Projects tab and let me know if your name reflects as the assignee

**Comment by Acclanugget** [comment]
Sure will do :) I will check it soon as I have stable internet

**Comment by Acclanugget** [comment]
I promise to do my part
